name: crypto_checker
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter_native_splash: ^2.3.6
  flutter_slidable: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  equatable: ^2.0.0
  flutter_bloc: ^8.0.0
  bloc: ^8.0.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_svg: ^2.0.9
  flutter:
    sdk: flutter
  path_provider: ^2.1.3
  http: ^1.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  build_runner:
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_launcher_icons:
  android: "launcher_icon" 
  ios: true
  image_path: "assets/icon/crypto_checker.png"
  min_sdk_android: 21
  
flutter:
  uses-material-design: true

  assets:
    - assets/images/token_icons/
    - assets/images/icons/
    - assets/images/crypto_currency_splash-screen.png

flutter_native_splash:
  background_image: assets/images/crypto_currency_splash-screen.png
  android_12:
    image: assets/images/crypto_currency_splash-icon.png
    color: "#03556b"
