name: crypto_checker
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  equatable: ^2.0.0
  flutter_bloc: ^8.0.0
  bloc: ^8.0.0
  shared_preferences: ^2.2.2
  intl: ^0.18.1
  flutter_svg: ^2.0.9
  flutter:
    sdk: flutter
  http: ^1.1.0

dev_dependencies:
  build_runner:
  hive_generator: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/token_icons/
