export interface Token {
  id: number;
  symbol: string;
  icon: string;
  bagSize: number;
  price: number;
  isVisible: boolean;
  percentage: number;
}

export const tokenAsset: Token[] = [
  {
    id: 1,
    symbol: 'BTC',
    icon: 'assets/images/token_icons/BTC.png',
    price: 0,
    bagSize: 0,
    isVisible: true,
    percentage: 0,
  },
  {
    id: 1027,
    symbol: 'ETH',
    icon: 'assets/images/token_icons/ETH.png',
    price: 0,
    bagSize: 0,
    isVisible: true,
    percentage: 0,
  },
  {
    id: 52,
    symbol: 'XRP',
    icon: 'assets/images/token_icons/XRP.png',
    price: 0,
    bagSize: 0,
    isVisible: true,
    percentage: 0,
  },
  {
    id: 5426,
    symbol: 'SOL',
    icon: 'assets/images/token_icons/SOL.png',
    price: 0,
    bagSize: 0,
    isVisible: true,
    percentage: 0,
  },
  {
    id: 2010,
    symbol: 'ADA',
    icon: 'assets/images/token_icons/ADA.png',
    price: 0,
    bagSize: 0,
    isVisible: true,
    percentage: 0,
  },
  {
    id: 3077,
    symbol: 'VET',
    icon: 'assets/images/token_icons/VET.png',
    price: 0,
    bagSize: 0,
    isVisible: true,
    percentage: 0,
  },
  {
    id: 74,
    symbol: 'DOGE',
    icon: 'assets/images/token_icons/DOGE.png',
    price: 0,
    bagSize: 0,
    isVisible: true,
    percentage: 0,
  },
  {
    id: 3890,
    symbol: 'MATIC',
    icon: 'assets/images/token_icons/MATIC.png',
    price: 0,
    bagSize: 0,
    isVisible: true,
    percentage: 0,
  },
  {
    id: 6210,
    symbol: 'SAND',
    icon: 'assets/images/token_icons/SAND.png',
    price: 0,
    bagSize: 0,
    isVisible: true,
    percentage: 0,
  },
  {
    id: 7080,
    symbol: 'GALA',
    icon: 'assets/images/token_icons/GALA.png',
    price: 0,
    bagSize: 0,
    isVisible: true,
    percentage: 0,
  },
  {
    id: 11145,
    symbol: 'PLS',
    icon: 'assets/images/token_icons/WPLS.svg',
    price: 0,
    bagSize: 0,
    isVisible: true,
    percentage: 0,
  },
  {
    id: 28928,
    symbol: 'HEX',
    icon: 'assets/images/token_icons/HEX.png',
    price: 0,
    bagSize: 0,
    isVisible: true,
    percentage: 0,
  },
  {
    id: 5015,
    symbol: 'eHEX',
    icon: 'assets/images/token_icons/eHEX.png',
    price: 0,
    bagSize: 0,
    isVisible: true,
    percentage: 0,
  },
  {
    id: 4038,
    symbol: 'MBL',
    icon: 'assets/images/token_icons/MBL.png',
    price: 0,
    bagSize: 0,
    isVisible: true,
    percentage: 0,
  },
  {
    id: 512,
    symbol: 'XLM',
    icon: 'assets/images/token_icons/XLM.svg',
    price: 0,
    bagSize: 0,
    isVisible: true,
    percentage: 0,
  },
  {
    id: 5805,
    symbol: 'AVAX',
    icon: 'assets/images/token_icons/AVAX.svg',
    price: 0,
    bagSize: 0,
    isVisible: true,
    percentage: 0,
  },
  {
    id: 1975,
    symbol: 'LINK',
    icon: 'assets/images/token_icons/LINK.png',
    price: 0,
    bagSize: 0,
    isVisible: true,
    percentage: 0,
  },
  {
    id: 3155,
    symbol: 'QNT',
    icon: 'assets/images/token_icons/QNT.svg',
    price: 0,
    bagSize: 0,
    isVisible: true,
    percentage: 0,
  },
];
